### ISSUE TITLE
Не хочу показаться идиотом...

### ISSUE THREAD

**Issue by ghost** [zobninatn/hh.ru-tasks#1]
Но их предложение расшаривать код на GitHub/Bitbucket выглядит, как минимум, странно. Погуглил здесь чисто ради интереса, задачи, видимо, одни и те же присылают всем (по крайней мере, у нас с тобой обе совпадают); ты был первым в списке, уверен, есть ещё полно таких же, и со временем их будет только больше.

Конечно, понимаю, что глупо воровать чужие решения, если не можешь написать своё, всё равно на собеседовании отсеют. Но всё-таки, сколько таких умников найдётся?.. Да и у добросовестных людей такой же соблазн слепить своё решение, анализируя чужие. HH.ru, таким образом, сами себе создают лишнюю головную боль.

Кажется, GitHub Gist наиболее адекватный способ передавать решения. Ни на GitHub, ни на Bitbucket нет возможности открывать доступ к репозиторию только тем, у кого есть ссылка -- Public всегда видны всем, а в Private необходимо вручную добавлять привилегированных пользователей.

Как-то глупо. Не понимаю их.

Успехов тебе!

**Comment by zobninatn** [comment]
Привет! Задачи, на самом деле, меняются. Я пробовал поступать еще в прошлом году и совпали только две задачи первого тура (с измененными входными данными) и одна второго тура. Это действительно странно, но, как мне кажется, итоговое решение на собеседовании будут принимать основываясь на таких факторах, как предыдущий опыт и адекватность.

Взаимно :)

**Comment by jenie-jenie** [comment]
Да, это всё само собой, просто странно. [Не хочешь посмотреть чьё-то решение про остров? :)](https://github.com/AndrewLrrr/Head-Hunter-School)
Ладно, ладно, пойду кодить.

**Comment by zobninatn** [comment]
В прошлом году тоже можно было найти решения, но смысл тогда, мне кажется, теряется. 
P.s. в любом случае, в этом году буду пытаться на джаве. А это тот еще прикол.

**Comment by jenie-jenie** [comment]
Не обратил внимания, скорее всего опечатка... Или это оползень от осадков :)
Угловые числа никакой роли не играют, впрочем, всё равно
